### ISSUE TITLE
AttributeError: module 'config' has no attribute 'use_sentry'

### ISSUE THREAD

**Issue by Furby667** [WiiLink24/food-server#26]
I tried to open "food.py" but it gave me an error saying that "AttributeError: module 'config' has no attribute 'use_sentry'"

Can Anybody Help?

**Comment by noahpistilli** [comment]
You need to rename config-example.py to config.py. Refer to the README.md for more info.

**Comment by Furby667** [comment]
Now It says "AttributeError: partially initialized module 'responses' has no attribute 'document_template'" can you help?
