### ISSUE TITLE
adding items to basket not working (deliveroo)

### ISSUE THREAD

**Issue by uonlywish5000** [WiiLink24/food-server#28]
Hello again, 

last time i was here it was coz of a patcher problem that i solved with help of the staff, after going loads of error etc i finally made it to the demae channel itself, but obviously another error had to greet me. When i add an item to the basket it gives me "Internet error: code 333500" i tried getting my wii closer to the router (btw my wii is like 2 stories from where the router is in my house). didnt work, so i connected my Wii again with it showing Excellent signal quality. but again same error, im not using any dns or stuff. does someone know the issue please?

**Comment by noahpistilli** [comment]
Deliveroo is no longer a service we offer.
